# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RXCollectionsTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'RXCollections', '~> 1.0'
  pod 'ReactiveObjC', '~> 3.1.0'
  pod 'libextobjc', '~> 0.3'
  pod '500-iOS-api', '~> 1.0.4'
  # Pods for RXCollectionsTest

end
